### ISSUE TITLE
Incorrect Warning: Unexpected input(s) 'checksNotification', valid inputs are ['fileName', 'noChangelogLabel', 'checkNotification']

### ISSUE THREAD

**Issue by matheus23** [Zomzog/changelog-checker#31]
We're getting a warning when running the changelog checker action as described in the readme: https://github.com/fission-suite/webnative/actions/runs/1037261430

> Unexpected input(s) 'checksNotification', valid inputs are ['fileName', 'noChangelogLabel', 'checkNotification']

But from looking at the code and readme, it looks like `Simple` and `Detailed` should be the valid inputs, right?

**Comment by Zomzog** [comment]
It's `checkNotification` and not `checksNotification` I will fix the README.
